// Generated by CoffeeScript 1.12.7
var _, bower, get_cwd_deps, latest, log, logger, version;

bower = require("bower");

_ = require("lodash");

logger = require("./logger");

log = logger.create("replace");

latest = function(dep) {
  if (dep.update && dep.update.latest) {
    return dep.update.latest;
  } else {
    return "?";
  }
};

version = function(dep) {
  if (dep.update && dep.update.target) {
    return dep.update.target;
  } else if (dep.pkgMeta && dep.pkgMeta.version) {
    return dep.pkgMeta.version;
  } else {
    return "?";
  }
};

get_cwd_deps = function(cb) {
  var available;
  available = [];
  return bower.commands.list().on("end", function(results) {
    return cb(_.filter(_.map(results.dependencies, function(dep, name) {
      return {
        name: name,
        version: version(dep),
        latest: latest(dep)
      };
    }), function(dep) {
      return dep.version !== dep.latest;
    }));
  });
};

module.exports = {
  available: get_cwd_deps
};
